[package]
name = "gift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fake-useragent = "0.1.3"
itertools = "0.12.0"
reqwest = "0.11.23"
tokio = { version = "1.35.1", features = ["full"] }